TasksManager/TasksManager/urls.py
from django.contrib import admin
from django.urls import path, include

urls_ = [
    path('admin/', admin.site.urls),
    path('', include('tasks.urls')),
    path('dashboard/', include('tasks.urls')),
    path('.*/', include('tasks.urls'))
]
urlpatterns = urls_

TasksManager/tasks/urls.py
from django.urls import path, include
from . import views

urls_ = [
    path('', views.redir),
    path('signin/', views.create),
    path('dashboard/add/', views.dashboard_add),
    path('dashboard/<str:team_url>/', views.dashboards),
    path('tasks/<int:task_id>/edit/', views.edit),
    path('tasks/<int:task_id>/delete/', views.delete_task),
    path('<str:exit_url>/exit/', views.exit_team),
    path('tasks/<int:task_id>/done/', views.done),
    path('me/', views.profile),
    path('', include('django.contrib.auth.urls')),
    path('dashboard/<str:d_url>/join/', views.dashboard_join),
]
urlpatterns = urls_

TasksManager/tasks/models.py
from django.db import models
from django.contrib.auth.models import User


class Task(models.Model):
    # кто должен сделать задание
    name = models.ForeignKey(User, on_delete=models.CASCADE)
    # срок сдачи
    deadLine = models.DateField()
    # письменное описание задания
    task = models.TextField()
    # на сколько сделано задание
    progerssBar = models.PositiveSmallIntegerField(default=0)
    # комнда где находится задание
    team = models.ForeignKey('AllTeams', on_delete=models.CASCADE)

    def __str__(self):
        return str(self.name) + ' ' + str(self.task) + ' ' + str(self.progerssBar)


class AllTeams(models.Model):
    # уникальный url для доски задний
    url = models.SlugField(unique=True)
    # название команды
    name = models.CharField("Назавание комнады: ", max_length=32)
    # все участники доски
    dashboards = models.ManyToManyField(User)

    def __str__(self):
        return str(self.url) + ' ' + str(self.name) + ' ' + str(self.dashboards.all())

    class Meta:
        verbose_name = 'Dashboard'
        verbose_name_plural = 'Dashboards'

TasksManager/tasks/forms.py
from django import forms
from .models import Task, AllTeams


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        exclude = ["team"]


class AllTeamsForm(forms.ModelForm):
    class Meta:
        model = AllTeams
        exclude = ["dashboards"]


class NameForm(forms.Form):
    name = forms.CharField()


class Pseudo(forms.Form):
    name = forms.CharField(label="name")
    task = forms.CharField(label="task")
    deadLine = forms.CharField(label="deadLine")
    progressBar = forms.IntegerField(label="progressBar")

TasksManager/tasks/views.py
import random

from django.http import HttpResponseRedirect
from django.contrib.auth.models import User, Group
from django.shortcuts import render, redirect, get_object_or_404
from .forms import TaskForm, NameForm, AllTeamsForm, Pseudo
from .models import Task, AllTeams
from django.contrib.auth.hashers import make_password
from django.utils import timezone
from django.core.exceptions import PermissionDenied
import datetime

def dashboards(request, team_url):
    if not request.user.is_authenticated:
        return redirect('/login')
    all_task_list = Task.objects.filter(team__url=team_url)
    name_list = AllTeams.objects.get(url=team_url).dashboards.all()
    # Добавление задачи
    form = TaskForm(request.POST or None)
    if request.method == "POST" and form.is_valid():

        q = Task(name=form.cleaned_data['name'],
                 deadLine=form.cleaned_data['deadLine'],
                 task=form.cleaned_data['task'],
                 progerssBar=form.cleaned_data['progerssBar'],
                 team=AllTeams.objects.get(url=team_url)
                 )
        q.save()
        return redirect('/dashboard/' + team_url + "/")
    else:
        form = TaskForm()

    # Все доски
    dashboards_list = AllTeams.objects.filter(dashboards__username=request.user.username)

    # Создание доски
    dashboard = AllTeamsForm(request.POST or None)
    if request.method == "POST" and dashboard.is_valid():
        d_board = AllTeams(url=dashboard.cleaned_data['url'], name=dashboard.cleaned_data['name'])
        q = request.user
        d_board.save()
        d_board.dashboards.add(q)
        return redirect('/dashboard/' + d_board.url + "/")

    # Присоединение к команде
    if request.method == "POST":
        r = request.user
        d_url = request.POST['join_url']
        try:
            d = AllTeams.objects.get(url=d_url)
            AllTeams.objects.get(url=d_url).dashboards.add(r.id)
            return redirect('/dashboard/' + d_url + "/")
        except AllTeams.DoesNotExist:
            return redirect('/dashboard/' + team_url + "/")
    return render(request, 'tasks/main.html',
                  {'all_task_list': all_task_list,
                   'form': form, 'name_list': name_list,
                   'dashboards_list': dashboards_list,
                   'user': request.user,
                   'dashform': dashboard,
                   'team': AllTeams.objects.get(url=team_url),
                   'now': timezone.now().date()
                   })


def edit(request, task_id):
    taskobj = get_object_or_404(Task, id=task_id)
    name_list = AllTeams.objects.get(url=taskobj.team.url).dashboards.all()
    form = TaskForm(request.POST or None, instance=taskobj)
    if request.method == "POST" and form.is_valid():
        form.save()
        return redirect('/dashboard/' + taskobj.team.url + "/")
    else:
        form = TaskForm(instance=taskobj)
    return render(request, 'tasks/edit.html', {'form': form, 'name_list': name_list, 'task': taskobj})


def profile(request):
    if not request.user.is_authenticated:
        return redirect("/login")
    dashboards_list = AllTeams.objects.filter(dashboards__username=request.user.username)
    try:
        if request.method == "POST":
            # Проверка на правильность ввода url
            check = AllTeams.objects.get(url=request.POST['url'])
            return redirect('/dashboard/' + request.POST['url'] + "/" + "join/")
    except AllTeams.DoesNotExist:
        return redirect("/me")
    return render(request, 'tasks/profile.html',
                  {'dashboards_list': dashboards_list, 'user': request.user})


def create(request):
    error = None
    if request.method == "POST":
        if not User.objects.filter(username=request.POST['username']):
            # Создание юзера по обработке пост запроса
            q = User(username=request.POST['username'],
                     first_name=request.POST['first_name'],
                     last_name=request.POST['last_name'], )
            q.password = make_password(password=request.POST['password'])
            q.id = random.randint(0, 1e10)
            q.save()
            # Юзер - обычный пользователь сайта
            q.groups.add(Group.objects.get(name="Member"))
            return redirect('/login')
        else:
            # если имя пользователя занято то высветим ошибку
            error = "Никнейм занят"
    return render(request, 'tasks/index.html', {'error_message': error})


def dashboard_add(request):
    if not request.user.is_authenticated:
        return redirect('/login')
    dashboard = AllTeamsForm(request.POST or None)
    if request.method == "POST" and dashboard.is_valid():
        d_board = AllTeams(url=dashboard.cleaned_data['url'], name=dashboard.cleaned_data['name'])
        q = request.user
        d_board.save()
        d_board.dashboards.add(q.id)
        return redirect('/dashboard/' + d_board.url + "/")
    return render(request, 'tasks/create_dash.html', locals())


def dashboard_join(request, d_url):
    if not request.user.is_authenticated:
        return redirect("/login")
    r = request.user  # пользователь
    d = AllTeams.objects.get(url=d_url)  # доска
    # проверка проходит на странице ввода url
    AllTeams.objects.get(url=d_url).dashboards.add(r)
    return redirect('/dashboard/' + d_url + "/")

def delete_task(request, task_id):
    if not request.user.is_authenticated:
        return redirect("/login")
    task = get_object_or_404(Task, id=task_id)
    team = task.team
    task.delete()
    return redirect('/dashboard/' + team.url + "/")


def redir(request):
    if request.user.is_authenticated:
        return redirect('/me/')
    else:
        return redirect('/login/')


# Выход из команды
def exit_team(request, exit_url):
    if not request.user.is_authenticated:
        return redirect("/login")
    r = request.user
    AllTeams.objects.get(url=exit_url).dashboards.remove(r.id)
    if AllTeams.objects.filter(dashboards__username=r.username):
        first_team = AllTeams.objects.filter(dashboards__username=r.username)[0].url
        return redirect("/dashboard/" + first_team)
    else:
        return redirect("/me/")


def done(request, task_id):
    if not request.user.is_authenticated:
        return redirect("/login")
    task = Task.objects.get(id=task_id)
    if not task.team.dashboards.filter(username=request.user.username):
        raise PermissionDenied
    task.progerssBar = 100
    task.save()
    return redirect('/dashboard/' + task.team.url)

TasksManager/tasks/templates/tasks/aboutDB.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- CSS only -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
          integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <!-- JS, Popper.js, and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
            integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
            crossorigin="anonymous"></script>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-lg-4 col-lg-offset-4">
            <h1 class="title">Создайте новую задачу</h1>
            <div>

                {{ url }}
                {{ name }}
                {{ deadLine}}
                {{ task }}
                {{ progressBar }}
            </div>
        </div>
    </div>
</div>
</body>
</html>

TasksManager/tasks/templates/tasks/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- CSS only -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
          integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <!-- JS, Popper.js, and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
            integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
            crossorigin="anonymous"></script>
    <meta charset="UTF-8">
    <title>Добавить задание. Task Manager</title>

    <style>
        .list-group-item {
            margin: 0 auto;
            padding-left: 50px;
            width: 30%;
        }


    </style>
</head>
<body background="https://avatanplus.com/files/resources/original/577c80ded65a0155be57669e.jpg">
<nav class="navbar navbar-dark bg-dark py-2" style="margin-bottom: 1em">
    <div>
        <a class="navbar-brand">TasksManager</a>
    </div>
</nav>
<br>
<div class="list-group">
    <a class="list-group-item list-group-item-action active mark">
        Создайте новую задачу
    </a>
    <form action="" method="post">{% csrf_token %}
        <a class="list-group-item list-group-item-action">
            <tr>
                <th><label for="id_name">Выполняющий:</label></th>
                <br>
                <td><select name="name" required id="id_name">
                    {% for name in name_list %}
                        <option value="{{ name.id }}">{{ name }}</option>
                    {% endfor %}
                </select></td>
            </tr>
        </a>

        <a class="list-group-item list-group-item-action">
            <tr>
                <th><label for="id_task">Описание:</label></th>
                <br>
                <td><textarea name="task" cols="40" rows="5" required id="id_task"></textarea></td>
            </tr>
        </a>

        <a class="list-group-item list-group-item-action">
            <tr>
                <th><label for="id_deadLine">Срок сдачи:</label></th>
                <br>
                <td><input type="date" name="deadLine" required id="id_deadLine"></td>
            </tr>
        </a>

        <a class=" list-group-item list-group-item-action">
            <tr>
                <th><label for="id_progerssBar">Прогресс:</label></th>
                <br>
                <td>
                    <input type="number" name="progerssBar" min="0" required id="id_progerssBar">
                </td>
            </tr>
        </a>

        <a class="list-group-item list-group-item-action">
            <button type="submit" class="btn btn-primary" style="margin-top: 10px">Добавить</button>
        </a>


    </form>

</div>

</body>
</html>

TasksManager/tasks/templates/tasks/create_dash.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- CSS only -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
          integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <!-- JS, Popper.js, and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
            integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
            crossorigin="anonymous"></script>
    <meta charset="UTF-8">
    <title>Создать доску. Task Manager</title>
    <style>
        .list-group-item {
            margin: 0 auto;
            padding-left: 50px;
            width: 30%;
        }


    </style>
</head>
<body style="background: url(https://avatanplus.com/files/resources/original/577c80ded65a0155be57669e.jpg)">
<nav class="navbar navbar-dark bg-dark py-2" style="margin-bottom: 1em">
    <div>
        <a class="navbar-brand" href="">TasksManager</a>
    </div>
</nav>
<div class="list-group" style="border-radius: 20px">
    <form action="" method="post"> {% csrf_token %}
        <a class="list-group-item list-group-item-action active mark">
            Создать новую доску
        </a>
        <a class="list-group-item list-group-item-action">
            <tr>
                <td><input type="text" name="url" maxlength="50" required id="id_url" placeholder="url"></td>
            </tr>
        </a>
        <a class="list-group-item list-group-item-action">
            <tr>
                <td><input type="text" name="name" maxlength="32" required id="id_name" placeholder="Название команды">
                </td>
            </tr>
        </a>
        <a class="list-group-item list-group-item-action">
            <button type="submit" class="btn btn-primary" style="margin-top: 10px">Создать</button>
        </a>
    </form>
</div>
</body>
</html>

TasksManager/tasks/templates/tasks/dashboard.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Задания. Task Manager</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
          integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
            integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
            crossorigin="anonymous"></script>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
            crossorigin="anonymous"></script>

    <style>
        .list-group-item {

            margin: 0 auto;
            padding-left: 50px;
            width: 55%;
        }
        .mark {
            margin: 0 auto;
        }


    </style>
    <title>Все задания</title>

</head>
<body background="https://million-wallpapers.ru/wallpapers/4/37/416169308315639.jpg">
<nav class="navbar navbar-dark bg-dark py-2" >
    <div>
        <a class="navbar-brand" href="/id/{{ user_name }}">TasksManager</a>
    </div>
</nav>
<p align="left" >
    <form action="javascript:history.back()">
    <button type="submit" class="btn btn-danger" style="margin-left: 15px">Назад</button>
</form>

    <a class="list-group-item list-group-item-action active mark">
        Все задания
    </a>
    {% for task in all_task_list %}
        <a class="list-group-item list-group-item-action">
            <h4> {{ task.name }}</h4>
            <em> {{ task.task }} </em>
            <br/><br/>
            <p> {{ task.deadLine }} </p>
            <form action="/{{ user_name }}/tasks/{{ task.id }}/edit">
                <button type="submit" class="btn btn-outline-info">Редактировать</button>
            </form>
        </a>
    {% endfor %}
    <a class="list-group-item list-group-item-action" href="/{{ user_name }}/tasks/{{ url }}/add/" style="color: #4e7edc">
        <br/>
        <svg width="2em" height="1em" viewBox="0 0 16 16" class="bi bi-plus-circle" fill="currentColor"
             xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd"
                  d="M8 3.5a.5.5 0 0 1 .5.5v4a.5.5 0 0 1-.5.5H4a.5.5 0 0 1 0-1h3.5V4a.5.5 0 0 1 .5-.5z"></path>
            <path fill-rule="evenodd" d="M7.5 8a.5.5 0 0 1 .5-.5h4a.5.5 0 0 1 0 1H8.5V12a.5.5 0 0 1-1 0V8z"></path>
            <path fill-rule="evenodd" d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"></path>
        </svg>
        Добавить задание
        <br>
        <br>
    </a>
</div>

</body>
</html>

TasksManager/tasks/templates/tasks/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Редактирование</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
          integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
            integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
            crossorigin="anonymous"></script>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
            crossorigin="anonymous"></script>

    <script>
        function confirmDialog() {
            var result = confirm("Вы действительно хотите удалить задание?");

            if (result) {
                location.href = "/tasks/{{ task.id }}/delete";
            }
        }
    </script>
</head>
<body style="background-image: url(https://avatanplus.com/files/resources/original/577c80ded65a0155be57669e.jpg)">
<div class="container-fluid justify-content-center col-6 py-md-5" style="margin: 1em auto auto;">

    <div class="card container-fluid" style="width: auto; padding: 1em; height: auto">
    <h3 style="text-align: center; margin-bottom: 40px; margin-top: 20px">Внесите изменения</h3>
        <form action="" method="post">{% csrf_token %}
            <tr style="margin: auto">
                <th><label for="id_name">Выполняющий:</label></th>
                <td><select name="name" required id="id_name">
                    <option value="{{ task.name.id }}">{{ task.name.first_name}} {{ task.name.last_name }}</option>
                    {% for name in name_list %}
                        {% if name != task.name %}
                            <option value="{{ name.id }}">{{ name.first_name}} {{ name.last_name }}</option>
                        {% endif %}
                    {% endfor %}
                </select></td>
            </tr>
            <hr/>
            <tr>
                <th><label for="id_deadLine">Срок сдачи:</label></th>
                <td><input type="date" name="deadLine" value='{{ task.deadLine.isoformat }}' required id="id_deadLine">
                </td>
            </tr>
            <hr/>
            <tr>
                <th><label class="col-3" for="id_task">Описание:</label></th>
                <td><textarea class="col-9" name="task" required id="id_task">{{ task.task }}</textarea></td>
            </tr>
            <hr/>
            <tr>
                <th><label for="id_progerssBar">Прогресс:</label></th>
                <td>
                    <input type="range" name="progerssBar"
                           min="0" max="100" required id="id_progerssBar" value='{{ task.progerssBar }}'>
                    <output id="ong" for="id_progerssBar">0</output>
                    <script>
                        $(function () {
                            var el;
                            $("#id_progerssBar").change(function () {
                                el = $(this);
                                el
                                    .next("#ong")
                                    .text(el.val() + "%");
                            })
                                .trigger('change');
                        });
                    </script>
                </td>
            </tr>
            <hr/>
            <div>
                <button type="submit" class="btn btn-primary btn-success" style="float: right; margin-left: 10px">Изменить</button>
                <a>
                    <button type="button" class="btn btn-primary btn-danger" id="delete_task" name="delete_task"
                            style="float: right" onclick="confirmDialog()">
                        Удалить
                    </button>
                </a>
                <a href="/dashboard/{{ task.team.url }}">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal" style="float: left">Отмена
                    </button>
                </a>
            </div>
        </form>
    </div>
</div>
</body>
</html>

TasksManager/tasks/templates/tasks/login.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v4.0.1">
    <title>Вход. Task Manager</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>


    <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/sign-in/">

    <!-- Bootstrap core CSS -->
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="{% static "../static\css\signin.css"%}" rel="stylesheet">
  </head>
  <body class="text-center">

    <form action="/l_redirect/" class="form-signin" method="post">{% csrf_token %}
        <input type="text" name="name" maxlength="32" required id="id_name" placeholder="Введите никнейм">
        <br/>
        <br/>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Войти</button>
        <br/>
        <p> <a href="/signin/">Зарегистрироваться</a></p>
    </form>

  </body>
</html>